# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e18ad096d6a4c48e451b636859ffcd4c02c938b2c78e6a0089024c37b9d371f7fbd30b124d1bf32d96da2d82bfda855fb6fa9668864d249ede1c29b8d78b0fe

test:
  secret_key_base: f3527d685dbedbfbc105bf0a95dc199013bcdfc817c7876a6ee508ad5fcb70915154a2ea0d13559f9ce14420bc3f9d4bff80dbdabaf443ee1ff4e08b3bb5edfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
